artist_array = [
    "Queen",
    "Lynyrd Skynyrd",
    "Foo Fighters",
    "Dire Straits",
    "Red Hot Chilli Peppers",
    "Zakk Wylde",
    "Slayer",
    "The Rolling Stones",
    "Creedence Clearwater Revival",
    "John Mayer",
    "Guns N Roses",
    "Metallica",
    "Eric Clapton",
    "Greenday",
    "Radiohead",
    "Oasis",
    "Blur",
    "ACDC",
    "Led Zeppelin",
    "Jimi Hendrix",
    "The Doors",
    "Rage Against the Machine",
    "Pink Floyd",
    "Aerosmith",
    "Black Sabbath",
    "ZZ Top",
    "Bob Dylan",
    "Elvis Presley",
    "The White Stripes",
    "Ed Sheeran",
    "Johnny Cash",
    "The Eagles",
    "The Beatles",
    "Chet Atkins",
    "The Lumineers",
    "Megadeth",
    "Chuck Berry",
    "John Lennon",
    "BB King",
    "The Clash",
    "Fleetwood Mac",
    "Santana",
    "Iron Maiden",
    "Buddy Holly",
    "Jeff Buckley",
    "Snow Patrol",
    "King Crimson",
    "Bob Marley",
    "Joan Jett",
    "Taylor Swift",
    "Van Halen"
]
